### DISCUSSION TITLE
Share your themes with us 🎨

### DISCUSSION THREAD

**Discussion by grtcdr** [grtcdr/macchina#222] [Show and tell]
**Got a cool theme?** 

Leave a screenshot of your macchina and your theme below. We'll pick the best ones and include them in the repository.

You get a cookie 🍪 if you **add in your theme's source**!

**Comment by di-effe** [comment]
Just because I forget where stuff is:

- [Theme Documentation](https://github.com/Macchina-CLI/macchina/wiki/Theme-Documentation)
- [Themes](https://github.com/Macchina-CLI/macchina/tree/main/themes)

**Comment by di-effe** [comment]
Logo is kinda s**t but I played a little around with Hydrogen to create something resembling the Dracula theme style.

![Dracula](https://raw.githubusercontent.com/di-effe/macchina-cli-themes/main/Dracula.png "Dracula theme")

I am using WSL2, hoping no one will get offended by it :D
May I offer some suggestions?

- Colors a quite few. Is it possible to use ANSI codes or hex?
- Not sure if I missed this, but it would be helpful to be able to customize the outer box too

**Reply by grtcdr** [reply]
> I am using WSL2, hoping no one will get offended by it :D
Hey, don't worry — WSL is a great tool, and definitely a good way to familiarize yourself with Linux :)

> Colors a quite few. Is it possible to use ANSI codes or hex?

If you're asking about ANSIC color codes in the ASCII art itself, then it is possible. It's not as intuitive as I'd like it to be, but we do support that.

> Not sure if I missed this, but it would be helpful to be able to customize the outer box too

That's coming in v6, see #200.

**Reply by di-effe** [reply]
Sorry, I was not clear.
I meant the colors that can be used for example in 
key_color = "Cyan"

**Reply by grtcdr** [reply]
Indexed colors and hexadecimal colors are also coming in v6 :)

**Reply by di-effe** [reply]
Nevermind, just saw #193

**Comment by grtcdr** [comment]
Here's mine :)

![2022-03-14T22:17:48,360563660+01:00](https://user-images.githubusercontent.com/35816711/158263650-a6278204-4dff-44fa-9ecf-4d2ee10e236c.png)

[Here's the sauce](https://gist.github.com/grtcdr/528cfd949788d3a14658727cd2f7f0ae)

**Comment by Dan1jel** [comment]
Here is my take on Dracula, would be nice with some extra color customizing, like border color, titel color and text color. Also this is all information available, i can't get battery and other stuff to work on termux. 

![Screenshot_20220418-085212](https://user-images.githubusercontent.com/4266424/163774760-137a0c36-6ce1-4065-8030-8a9ecf350d3d.png)

**Comment by gmarsanich** [comment]
![image](https://user-images.githubusercontent.com/90848381/168396667-b4a24c71-6acd-4e96-9d32-a68be66d2f6f.png)
This is mine ^

the [sauce](https://pastebin.com/CTTreAh5) and the [ASCII art](https://pastebin.com/hnJJrBSW)

**Reply by grtcdr** [reply]
That looks really really cool :smile:

**Comment by Lovasz-Akos** [comment]
![image](https://user-images.githubusercontent.com/55391231/178102266-b7edea6f-44a8-4f13-a475-c57d77f0d24e.png)

Here's my theme, [Naara](https://gist.github.com/Lovasz-Akos/073131d75eeb133fc4e4a37fb8c8cbe9)!
Terminal color scheme is Steven Follis's [Powershell profile](https://gist.github.com/stevenfollis/ddd6cd0f50b95f0cff70d6c8105276ac) made to match the [Panda](http://panda.siamak.me/) color scheme <3

**Reply by grtcdr** [reply]
Absolutely beautiful :)

**Comment by mezoracs** [comment]
heeey this is my red-scheme theme, hope u like. **obs:** i'm using [Liga SF mono nerd font](https://github.com/shaunsingh/SFMono-Nerd-Font-Ligaturized). oh i use arch btw

![myimage_000](https://user-images.githubusercontent.com/107153321/183230909-c08593c8-059c-4aaa-994c-3196efa99d98.png)

you can get the code at my [dotfiles](https://github.com/mezoracs/mz_dotfiles) inside macchina folder c:

**Reply by yarinbar** [reply]
nice work but the link is 404ing for me

**Reply by grtcdr** [reply]
> nice work but the link is 404ing for me

Try [this](https://github.com/mezoracs/mz_dotfiles).

**Reply by mezoracs** [reply]
hey i'm sorry, just update my repo name..

this is the new link :) [repo](https://github.com/mezoracs/mz_dotfiles)

**Reply by yarinbar** [reply]
Thanks! I think i have a bug where all the info is always shown. For example, i copy pasted your config and got the following:
![image](https://user-images.githubusercontent.com/37772157/186212117-e82bddc3-535e-4818-9651-d75934f5921e.png)

All of the info is there even though it is not in the config. It happens with all other themes too, do you have any idea how to fix this?

**Reply by mezoracs** [reply]
Heyy! Yeahh to use just selected info sections, you must use the flag `--show` and the section you want... You can get all the list using `macchina --help`, hope i've helped you :)

Pd: This is the instruction i use at config: `macchina --theme mezora --show Host Kernel Distribution Packages DesktopEnvironment Memory ProcessorLoad Shell Terminal WindowManager Battery`

**Comment by luccahuguet** [comment]
this is mine, that I built upon `mezora`!

![image](https://user-images.githubusercontent.com/27565287/227753209-bcfbc0de-26da-4396-85ea-65b1d131054a.png)

```toml
[keys]
host       =  "🏚  host"
# host       =  "⌂  host"
machine    =  "💻 machine" 
kernel     =  "⚙️  kernel"
distro     =  "❇  distro"
packages   =  "📦 packages"
terminal   =  "🗔  terminal"
shell      =  "꩜  shell"
cpu        =  "⚔  cpu"
cpu_load   =  "📈 cpu load"
memory     =  "⚔  memory"
battery    =  "🔋 battery"
uptime     =  "⏱️  uptime"
resolution =  "📽  resolution"
backlight  =  "🕯️  brightness"
de         =  "💻 de"
wm         =  "🗗  wm"
```

the project has been very useful, ty for the work

**Comment by flinesse** [comment]
✨ Ricing is my passion ✨

![Screenshot 2023-10-14 at 6 18 27 PM](https://github.com/Macchina-CLI/macchina/assets/31031753/6ee09722-13c4-4a61-beb8-df7f4b27ae21)


Now I have a boring minimal one to run on startup and a gaudy one for (no one) who happens to walk by. Thanks team!!

**Reply by flinesse** [reply]
Following the naming scheme of course — [Oganesson.toml](https://gist.github.com/flinesse/4623c4e62019434e3abb619fb0e5a8a8)

**Reply by flinesse** [reply]
![image](https://github.com/Macchina-CLI/macchina/assets/31031753/2d52b2c4-0bfd-49c2-aa53-2a4297b42ba8)

**Reply by Wangch29** [reply]
where's your apple-ascii?

**Comment by gmarsanich** [comment]
decided it was time for an update
here's the [sauce](github.com/gmarsanich/macchinacfg2) :)
![image](https://github.com/Macchina-CLI/macchina/assets/90848381/99f3fe21-f5e6-4f89-b710-bb6ef97e0f53)

**Comment by trollLemon** [comment]
Saw this discussion board and got inspired to make my own theme.  I decided to call it Bismuth since the ASCII art sort of reminded me of Bismuth crystals.
![20231201_11h21m42s_grim](https://github.com/Macchina-CLI/macchina/assets/90001607/6e202a22-c46b-4a3c-a3ab-174ad7e5efd2)
The source is in the macchina directory of my dot files repo:https://github.com/trollLemon/dots/tree/main/config/macchina/themes

**Comment by WiredBun** [comment]
![Screenshot_2024-05-17_07-53-58](https://github.com/Macchina-CLI/macchina/assets/45413840/f6c1be6a-7733-469c-ad8f-f47227309110)
its very basic but i only set up macchina last night and made this by cloning lithium and going through the customization wiki point by point

**Reply by grtcdr** [reply]
It gives off a hacker vibe. I like it :)

**Comment by lycheeje11y** [comment]
This one is built off of @gmarsanich's yttrium theme. Still a wip but...
![Screenshot 2024-05-24 at 9 18 46 AM](https://github.com/Macchina-CLI/macchina/assets/118591147/72ad1f69-823a-44b5-a026-0c3046238ce2)
The dotfiles are [here](https://github.com/s4Dt0y/rb-dotfiles)

**Comment by omarluq** [comment]
Luffytaro 🤓 
Source code: https://github.com/omarluq/luffytaro

![Luffytaro](https://github.com/Macchina-CLI/macchina/assets/84993125/069b93fe-e87c-4ee5-9659-479bfd5fc08f)

**Comment by espeon** [comment]
i built mine off helium
source: https://github.com/espeon/astatine

![image](https://github.com/Macchina-CLI/macchina/assets/22222885/1b2b0628-1a7d-49f4-acbd-1c249f3b044d)

**Comment by hyperb1iss** [comment]
This is [elektra](https://github.com/hyperb1iss/elektra), based on astatine

![screenshot](https://github.com/user-attachments/assets/018e3e42-7f20-4094-a903-ebba7dd19325)

**Comment by KPCOFGS** [comment]
![Screenshot from 2024-12-01 23-23-04](https://github.com/user-attachments/assets/6a5f4f38-d141-47a3-b465-8e0e5fd38993)

**Reply by HirresJoe** [reply]
please show you config

**Reply by HirresJoe** [reply]
where is ascii.txt

**Comment by Lovasz-Akos** [comment]
![image](https://github.com/user-attachments/assets/cc4dfe26-3a68-46a1-a2cb-c98896e5947c)
been a while since I shared, looks a lot different now :D

**Comment by Anant-mishra1729** [comment]
Pika-pi!!  😊
Source: https://github.com/Anant-mishra1729/Dotfiles

<img width="1886" height="972" alt="image" src="https://github.com/user-attachments/assets/29a3c4d0-8d0d-4e9e-bafc-16d7851ffba8" />

**Comment by Altrabeth** [comment]
## Catppuccin (Latte, Frappe, Macchiato, Mocha)

I went looking for a [Catppuccin](https://github.com/catppuccin/catppuccin) theme for macchina and couldn't find one anywhere, so here are all four flavors.

Each uses its flavor's Mauve for the keys and Overlay 0 for the separator, with hex values from [catppuccin/palette](https://github.com/catppuccin/palette). If your terminal is already on a Catppuccin flavor, use the matching one and it'll sit right on your background. The bars inherit `key_color`, so the filled segments come out in the accent automatically.

Save any of these to `~/.config/macchina/themes/` and run `macchina --theme CatppuccinMocha`, or set `theme = "CatppuccinMocha"` in `macchina.toml`.

<details>
<summary><b>CatppuccinMocha.toml</b></summary>

```toml
# Catppuccin Mocha
#
# Part of the Catppuccin family: Latte, Frappe, Macchiato, Mocha.
# Palette: https://github.com/catppuccin/catppuccin
#   Mauve #cba6f7 (keys) — Overlay 0 #6c7086 (separator) — Base #1e1e2e

spacing         = 1
padding         = 0
separator       = "›"
key_color       = "#cba6f7"
separator_color = "#6c7086"

[box]
title           = "Catppuccin Mocha"
border          = "rounded"
visible         = true

[box.inner_margin]
x               = 1
y               = 0

[palette]
type            = "Full"
glyph           = "● "
spacing         = 2
visible         = true

[bar]
glyph           = "■"
symbol_open     = '['
symbol_close    = ']'
hide_delimiters = false
visible         = true
```
</details>

<details>
<summary><b>CatppuccinMacchiato.toml</b></summary>

```toml
# Catppuccin Macchiato
#
# Part of the Catppuccin family: Latte, Frappe, Macchiato, Mocha.
# Palette: https://github.com/catppuccin/catppuccin
#   Mauve #c6a0f6 (keys) — Overlay 0 #6e738d (separator) — Base #24273a

spacing         = 1
padding         = 0
separator       = "›"
key_color       = "#c6a0f6"
separator_color = "#6e738d"

[box]
title           = "Catppuccin Macchiato"
border          = "rounded"
visible         = true

[box.inner_margin]
x               = 1
y               = 0

[palette]
type            = "Full"
glyph           = "● "
spacing         = 2
visible         = true

[bar]
glyph           = "■"
symbol_open     = '['
symbol_close    = ']'
hide_delimiters = false
visible         = true
```
</details>

<details>
<summary><b>CatppuccinFrappe.toml</b></summary>

```toml
# Catppuccin Frappe
#
# Part of the Catppuccin family: Latte, Frappe, Macchiato, Mocha.
# Palette: https://github.com/catppuccin/catppuccin
#   Mauve #ca9ee6 (keys) — Overlay 0 #737994 (separator) — Base #303446

spacing         = 1
padding         = 0
separator       = "›"
key_color       = "#ca9ee6"
separator_color = "#737994"

[box]
title           = "Catppuccin Frappe"
border          = "rounded"
visible         = true

[box.inner_margin]
x               = 1
y               = 0

[palette]
type            = "Full"
glyph           = "● "
spacing         = 2
visible         = true

[bar]
glyph           = "■"
symbol_open     = '['
symbol_close    = ']'
hide_delimiters = false
visible         = true
```
</details>

<details>
<summary><b>CatppuccinLatte.toml</b></summary>

```toml
# Catppuccin Latte
#
# Part of the Catppuccin family: Latte, Frappe, Macchiato, Mocha.
# Palette: https://github.com/catppuccin/catppuccin
#   Mauve #8839ef (keys) — Overlay 0 #9ca0b0 (separator) — Base #eff1f5

spacing         = 1
padding         = 0
separator       = "›"
key_color       = "#8839ef"
separator_color = "#9ca0b0"

[box]
title           = "Catppuccin Latte"
border          = "rounded"
visible         = true

[box.inner_margin]
x               = 1
y               = 0

[palette]
type            = "Full"
glyph           = "● "
spacing         = 2
visible         = true

[bar]
glyph           = "■"
symbol_open     = '['
symbol_close    = ']'
hide_delimiters = false
visible         = true
```
</details>

Only three things in macchina actually take a color (`key_color`, `separator_color`, `[custom_ascii].color`), so if you want a different accent just swap `key_color` — Blue (`#89b4fa` on Mocha), Teal (`#94e2d5`) and Peach (`#fab387`) all work well. Each file has its flavor's palette in a comment at the top.

I also opened https://github.com/Macchina-CLI/macchina/pull/366 to add these to `contrib/themes/`, in case they are wanted upstream.
