### ISSUE TITLE
🚨 Announcement: `v4`'s breaking changes! 🚨

### ISSUE THREAD

**Issue by grtcdr** [grtcdr/macchina#170]
macchina is ~~undergoing~~ has undergone lots of reconstruction, let me explain why.

I think themes are a great idea, and they're likely never to go away.

Why?
- They keep your configuration separate from the visual tweaks
- They can be easily shared with others

With the introduction of themes, macchina's flags became redundant, and in some cases clashed with your theme's configuration (like the color setting for example). Now, we *could* fix this, but this wouldn't eliminate the problem. Little bugs will  continue to creep up and cause headaches for us as maintainers of the project, and you, as a user (_thank you_, by the way).

We don't want macchina to be complicated; so I suggest we use **themes for customization**, and **macchina.toml for configuration**.

### PR #171 (#172)

This PR deprecates the following flags:
- `--show-only` (now named `--show`)
- `--hide` (gone forever...)
- `--padding` (can only be set by themes)
- `--spacing` (can only be set by themes)
- `--color` (can only be set by themes)
- `--box-title` (can only be set by themes)
- `--short-uptime` (now named `--long-uptime`)
- `--separator-color` (can only be set by themes)
- `--box-inner-margin-x` (moved to and can only be set by themes)
- `--box-inner-margin-y` (moved to and can only be set by themes)

Now that themes files have gotten some new additions, you might be thinking "What the hell, grtcdr! I can't read JSON!"
Don't worry friend, I plan to move themes from JSON to TOML, see #172.

You probably _hate_ me by now, after all this'll be the third time your configs suddenly broke because of non-backwards compatible changes, but this is for the best.

## Before (JSON)
```json
{
   "spacing": 2,
   "padding": 0,
   "separator": "->",
   "bar": {
      "Custom": {
         "visible": true,
         "glyph": "ߋ",
         "symbol_open": "[",
            "symbol_close": "]"
      }
   },
   "box": {
      "title": " 🎉 v4.0 ",
      "visible": true,
      "inner_margin":
      {
         "x": 4,
         "y": 1
      }
   },
   "custom_ascii": {
      "color": "Blue"
   },
   "randomize": {
      "key_color": true,
      "separator_color": false
   },
   "keys": {
      "host": "HOST",
      "kernel": "KERN",
      "battery": "BAT",
      "os": "OS",
      "de": "DE",
      "wm": "WM",
      "distro": "DIST",
      "terminal": "TERM",
      "shell": "SHELL",
      "packages": "PKGS",
      "uptime": "UPTIME",
      "memory": "MEM",
      "machine": "MACH",
      "local_ip": "LOCAL IP",
      "backlight": "BRI",
      "resolution": "RES",
      "cpu_load": "CPU LOAD",
      "cpu": "CPU"
   },
   "color": {
      "Rgb": [
         231,
         198,
         100
      ]
   },
   "separator_color": {
      "Rgb": [
         158,
         208,
         114
      ]
   }
}
```

## After (TOML)
```toml
spacing = 2
padding = 0
separator = "-"

[bar]
glyph = "x"
symbol_open = '('
symbol_close = ')'
visible = true

[box]
title = " 🎉 v4.0 "
visible = true

[box.inner_margin]
x = 4
y = 1

[custom_ascii]
color = "Blue"

[randomize]
key_color = true
separator_color = false

[keys]
host = "HOST"
kernel = "KERN"
battery = "BAT"
os = "OS"
de = "DE"
wm = "WM"
distro = "DIST"
terminal = "TERM"
shell = "SHELL"
packages = "PKGS"
uptime = "UPTIME"
memory = "MEM"
machine = "MACH"
local_ip = "LOCAL IP"
backlight = "BRI"
resolution = "RES"
cpu_load = "CPU LOAD"
cpu = "CPU"
```
#### What do YOU think?
