### ISSUE TITLE
When the Terminal startup, the stdout of macchina is truncated.

### ISSUE THREAD

**Issue by cooocy** [grtcdr/macchina#347]
**Describe the bug**
**This may not be the problem of `macchina`, I'm just reporting it here.**
My default shell is fish, when the Terminal startup, the fish shell will exec and run macchina, but the stdout of macchina is truncated. like this:

<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/e69cacfa-69ab-4f02-89bd-070fb5979d3c" />

When I run macchina again, the stdout is ok. I guess this has to do with the width and height of the Terminal(When the Terminal startup, the width and height are not obtained?).

<img width="992" alt="Image" src="https://github.com/user-attachments/assets/b44a068b-faf7-40dd-8599-75d27b3460d7" />

When I set `neofetch` as the default cmd to exec when fish startup, the stdout is ok too. 
In addition, the above bugs can also be reproduced in iTerm2.
<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/150c5bb0-fb61-42bb-89ed-29ba2afd7214" />

**To Reproduce**
1. Click Terminal

**Expected behavior**
The stdout of macchina is ok.

**Screenshots**

**`macchina --doctor` output**
<img width="1249" alt="Image" src="https://github.com/user-attachments/assets/c93debe7-0ca7-48a1-b96c-737f22ac3c3e" />

**`macchina.toml` contents**
If applicable, please include the contents of your `macchina.toml` configuration file in the following code block (remove any unnecessary comments):
```toml
# Specifies the network interface to use for the LocalIP readout
interface = "en0"

# Lengthen uptime output
long_uptime = true

# Lengthen shell output
long_shell = false

# Lengthen kernel output
long_kernel = false

# Toggle between displaying the current shell or your user's default one.
current_shell = true

# Toggle between displaying the number of physical or logical cores of your
# processor.
physical_cores = true

# Disks to show disk usage for. Defaults to `["/"]`.
disks = ["/"]

# Show percentage next to disk usage
disk_space_percentage = true

# Themes need to be placed in "$XDG_CONFIG_DIR/macchina/themes" beforehand.
# e.g.:
#  if theme path is /home/foo/.config/macchina/themes/Sodium.toml
#  theme should be uncommented and set to "Sodium"
#
theme = "Dress"

# Displays only the specified readouts.
# ProcessorLoad
show = ["Host", "Machine", "Kernel", "Distribution", "OperatingSystem", "DesktopEnvironment", "WindowManager", "Shell", "Terminal", "Packages", "Uptime", "LocalIP", "Resolution", "Backlight", "Battery", "Processor", "GPU", "Memory", "DiskSpace"]
```

**System Information**
You don't have to provide this information if you're not comfortable doing so, but it'll help us solve the issue a lot faster.
 - Operating System: MacOS Sequoia 15.0.1 (24A348)
 - Terminal: Hyper 3.4.1 (stable)
 - Macchina's version: macchina: 6.4.0; libmacchina:8.0.0
